language: python
python:
  - "3.7.3"
cache: pip
dist: xenial
services:
  - xvfb
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - xvfb-run -a --server-args="-screen 0 1366x768x24" pytest

