language: python
python:
  - "3.7.3"
cache: pip
dist: xenial
services:
  - xvfb
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - sudo add-apt-repository -y ppa:mc3man/trusty-media
  - sudo apt-get install -y ffmpeg
  - sudo apt-get install pulseaudio
  - dbus-launch pulseaudio --start
  - for file_py in */*.py; do pylint -E  --disable=E0401,E0602,E1101 $file_py; done
  - xvfb-run -a --server-args="-screen 0 1600x900x24" pytest

